#!/bin/bash

# Add xanmod in mhwd-kernel
if ! grep -q linux-xanmod /usr/bin/mhwd-kernel; then
    sed -i 's/\^linux\[0-9]\[0-9]?(\[0-9])\$/^linux[0-9][0-9]?([0-9])$|^linux-xanmod$/g' /var/lib/mhwd/scripts/mhwd
    sed -i 's/\^linux\[0-9]\[0-9]?(\[0-9])\$/^linux[0-9][0-9]?([0-9])$|^linux-xanmod$/g' /usr/bin/mhwd-kernel
    
    sed -i 's/current="linux$major$minor"/if uname -r | grep xanmod >&=; then current="linux-xanmod"; else current="linux$major$minor"; fi/g' /usr/bin/mhwd-kernel
fi